name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  test-backend:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: server

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run backend tests
        run: npm test

  test-frontend:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: client

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run frontend tests
        run: npm test

  build-images:
    runs-on: ubuntu-latest
    needs: [test-backend, test-frontend]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build & Push Backend
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/ushawty-backend:latest ./server
        docker push ${{ secrets.DOCKER_USERNAME }}/ushawty-backend:latest

    - name: Build & Push Frontend
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/ushawty-frontend:latest ./client
        docker push ${{ secrets.DOCKER_USERNAME }}/ushawty-frontend:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-images

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
            host: ${{ secrets.EC2_HOST }}
            username: ${{ secrets.EC2_USER }}
            key: ${{ secrets.EC2_SSH_KEY }}
            script: |
                # pull latest images
                docker pull ${{ secrets.DOCKER_USERNAME }}/ushawty-backend:latest
                docker pull ${{ secrets.DOCKER_USERNAME }}/ushawty-frontend:latest

                # run new containers (green)
                docker run -d -p 5002:5000 --name backend-green ${{ secrets.DOCKER_USERNAME }}/ushawty-backend:latest
                docker run -d -p 3002:80 --name frontend-green ${{ secrets.DOCKER_USERNAME }}/ushawty-frontend:latest

                echo "Waiting for backend health check..."

                # wait for backend to be ready
                for i in {1..10}; do
                    if curl -f http://localhost:5002/health; then
                    echo "Backend is healthy"
                    break
                    fi
                    echo "Retrying..."
                    sleep 2
                done

                # switch nginx to new ports
                sudo sed -i 's/3001/3002/g' /etc/nginx/nginx.conf
                sudo sed -i 's/5001/5002/g' /etc/nginx/nginx.conf
                sudo systemctl reload nginx

                # remove old containers
                docker stop frontend-blue || true
                docker rm frontend-blue || true
                docker stop backend-blue || true
                docker rm backend-blue || true

                # rename green → blue
                docker rename frontend-green frontend-blue
                docker rename backend-green backend-blue